capacitor-community/http

.gitignore, .npmignore, CapacitorCommunityHttp.podspec, README.md, ios/Plugin/Plugin.h, ios/Plugin/Plugin.m, ios/Plugin/Plugin.swift, ios/Podfile, ios/Podfile.lock, package-lock.json, package.json, rollup.config.js, src/definitions.ts, src/index.ts, src/web.ts, tsconfig.json
Decided to create this merge request for any further development. We use our own version in our project because it takes too long for updates to get pushed to npm.
Whats included:
- In the Swift version of `upload` headers weren't included
- Missing type definitions for `uploadFile`
- Simplify `uploadFile`
- Make iOS and Web Version Capacitor 3 ready (Android NOT included, because I don't have any experience with it and we haven't yet deployed to Google Play)
Feel free to use it as a reference or merge it into the cap-3 branch.
Just mention you here because I have seen you already took some effort into making it v3 ready @thomasvidas.
=> Update to Capacitor v3 and some bug fixes

android/src/main/java/com/getcapacitor/plugin/http/Http.java
When the request data is being obtained. They are added line by line and the line break is being omitted. Causing errors when parsing the data.
This error only occurs on Android
=> Fix (Android) add line break in GET request data

src/definitions.ts, src/web.ts
Adds optional `expires` to `HttpSetCookieOptions` type. If both the `expires` and `agesDays` options are set, the function will use `expires`.
Fixes #16
=> Add 'expires' option to Http.setCookie

ios/Plugin/Plugin.swift
Only modify the URL if the params map has values in it
Fixes #64
=> Fix for empty query params adding ? on ios

android/src/main/java/com/getcapacitor/plugin/http/Http.java
I'm currently having a problem with the HTTP plugin on Android.
Whenever I try to perform an HTTP request, it seems the javascript runtime hangs and only continues when there is a result from the HTTP plugin. This is very bad for my app because we need to perform some tasks in "background" mode and still allow the user to navigate within the app. 
I've implemented a workaround for this, which is included in this PR. I am not an expert in Android development, so I am not sure whether this is the best approach (I used a simple thread).
Suggestions and other workarounds are also welcome if this PR is not appropriate.
=> Perform android http requests in separate thread

android/src/main/java/com/getcapacitor/plugin/http/Http.java, ios/Plugin/Plugin.swift, src/definitions.ts, src/web.ts
Instead of just treating all responses as strings, consider `responseType` to properly encoding the data received from the server.
This should fix https://github.com/capacitor-community/http/issues/15
=> Fix for #15 Encode response according to `responseType`

android/src/main/java/com/getcapacitor/plugin/http/HttpRequestHandler.java
My previous fix for json null value (#90) doesn't work with capacitor-v3 anymore.
Because, com.getcapacitor.plugin.http.HttpRequestHandler#readStreamAsString add a new line on String.
I added .trim() on the json null value check and it works correctly again.
=> bugfix android json null value

src/request.ts
-Since the response type was meant for the ok response, use either 'text' or 'json' (if the 'content-type' header matches) to avoid parsing errors of an error response that might not conform to the specified response type in the HttpOptions.
-This behavior is consistent with the Android implementation of the plugin
=> Use the default response type if the response is not ok

ios/Plugin/Plugin.swift, src/web.ts
Any statuscode that is not in the range of 2xx should reject the downloadFile method invocation.
fixes #37
=> fix: reject downloadFile promise when statusCode not in 2xx range

android/src/main/java/com/getcapacitor/plugin/http/Http.java, ios/Plugin/Plugin.swift, src/web.ts
Currently, setting the cookie expiration via the `expires` or `ageDays` params does only work in the web version.
This PR adds the same functionality to the android/ios versions.
In addition, this PR updates the setCookies method in the web version to use case-insensitive replacement.
=> Add option to set cookie expiration in android/ios

.gitignore, android/src/main/java/com/getcapacitor/plugin/http/CapacitorHttpUrlConnection.java, android/src/main/java/com/getcapacitor/plugin/http/HttpRequestHandler.java, android/src/test/java/com/getcapacitor/plugin/http/HttpRequestHandlerTest.java, ios/Plugin/CapacitorUrlRequest.swift, ios/Plugin/HttpRequestHandler.swift
- Array request support
- Removing the extra new line from the plain text responses.
- Adding error property to response sent from plugin. 
- Array request support - there is probably better solution (maybe pushing plugin call variable down through methods) but this also works. As I am not experienced with swift tried to do as less mods as possible.
- There was no extra new line issue 
- I did not include error property for ios as existing implementations in ios and android are not the same (as I can see).
I don't have experience with java/swift but as I understood the code response implementations are not the same:
- Android plugin resolves (call.resolve) http errors - reads error stream and returns json object from readData
- ios plugin rejects (call.reject) http errors - if error …
=> Adding support for posting json arrays.

src/request.ts
The current web implementation seems to not include anything in the request body if the data property is a FormData object. In my opinion, the problem lays in iterating over the FormData content using Object.keys(), which doesn't seem to return anything for a FormData object. My suggestion is to use a separate FormData specific method to iterate over the FormData content.
-Since Object.keys() doesn't return anything for FormData typed objects, use a FormData specific function to iterate over the key/value pairs.
=> Add additional logic for FormData typed request bodies

ios/Plugin/CapacitorUrlRequest.swift, ios/Plugin/HttpRequestHandler.swift
This change moves parsing the "data" arg from JSValue into more specific types further down into the content-type specific handlers. The abstract capacitor `JSValue` is suitable for passing to the JSON serializer, so by doing this, we fix POST/PATCH/etc on iOS for data structures other than objects/dictionaries. This was important to me as I need to send an array as my POST body.
Additionally, when the request body sent to this plugin is improperly formed, we now explicitly throw before even making the request. This is both to ensure we don't send a malformed request, and also to provide the developer with some insight as to where and why the request is failing (specifically, I always want to know if the plugin is generating the error, or if the server is generating the error. Setting a …
=> (iOS) Fix: Allow non-object request bodies

android/src/main/java/com/getcapacitor/plugin/http/CapacitorHttpUrlConnection.java, android/src/main/java/com/getcapacitor/plugin/http/Http.java, android/src/main/java/com/getcapacitor/plugin/http/HttpRequestHandler.java, android/src/main/java/com/getcapacitor/plugin/http/JSValue.java, ios/Plugin/CapacitorUrlRequest.swift, ios/Plugin/HttpRequestHandler.swift
Does essentially the same as #141, but for android. The primary use-case for this is to be able to send content-type: application/json requests that _are_ valid JSON, but aren't plain objects (such as arrays and JS primitives).
Additionally, this fixes an existing bug where for multipart/form-data requests, the connection stream was being written to after it was closed, causing an IOException.
=> (Android) Fix: Allow non-object request bodies

ios/Plugin/HttpRequestHandler.swift, ios/Plugin/Plugin.swift
http method utility functions (ie: `Http.get({url: ''})`) do not currently work on iOS, the http method is not passed through to `HttpRequestHandler.request` properly and it throws `.dataNotAllowed`
=> fix http method helper functions on ios

android/src/main/java/com/getcapacitor/plugin/http/CapacitorHttpUrlConnection.java, android/src/main/java/com/getcapacitor/plugin/http/HttpRequestHandler.java, ios/Plugin/CapacitorUrlRequest.swift, ios/Plugin/HttpRequestHandler.swift, src/definitions.ts
This PR adds support for disabling automatic HTTP redirects on android/ios by setting the "disableRedirects" property in the HttpOptions object.
This functionality is already provided by the Cordova HTTP plugin [cordova-plugin-advanced-http](https://github.com/silkimen/cordova-plugin-advanced-http).
=> Add support for disabling automatic HTTP redirects on android/ios

src/request.ts
By default, in the native implementations, if content type is excluded and an object is passed for `data`, the content type will default to `application/json`. However, in the web impl, it defaults to `multipart/form-data`. This change makes the behavior of the web implementation more like the native implementations, so that consumers can do less `platformIs` switching.
I've also included a fix for `multipart/form-data` handling, as it does not work currently.
=> (web) Change content-type "detection" to prioritize application/json

android/src/main/java/com/getcapacitor/plugin/http/Http.java, android/src/main/java/com/getcapacitor/plugin/http/HttpRequestHandler.java, ios/Plugin/HttpRequestHandler.swift, ios/Plugin/Plugin.swift, src/definitions.ts, src/web.ts
Attempt at **partially** implementing #2 
The pull requests covers only downloadFile progress (but also places some foundation for uploadFile implementation and maybe even request support) since it seems like the best candidate for checking progress - when we use it we are probably downloading bigger files using it and it was easiest one to implement (no deep buried logic).
Pull request is marked as draft since I'm not sure if it should or can be merged without at least uploadFile support.
Will also try to implement ios support after getting convention/implementation/approval feedback.
For downloadFile only support we can drop generic interfaces in favor of ones like `download-progress` event or just only use `DOWNLOAD` ProgressType. 
Naming conventions and implementation methods of …
=> feat: downloadFile progress reporting support

android/src/main/java/com/getcapacitor/plugin/http/Http.java
This is a non-functional change (😬) that refactors the use of lambdas in the android project to instead be anonymous class instances.
An alternative may be adding the following to the android block of the build.gradle:
```groovy
compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}
```
Which would declare java 8 is required, and _may_ have fixed the build issues I was encountering in my CI system, but this was the more straightforward approach.
=> fix(android): Maintain java 7 support

android/src/main/java/com/getcapacitor/plugin/http/CapacitorHttpUrlConnection.java, ios/Plugin/CapacitorUrlRequest.swift
This change sets a default `Accept-Language` header on all requests based on the device's current locale preferences, in an effort to support further out-of-the-box parity between web and native implementations. On the web, the browser will set `Accept-Language` to the device's locale if not specified, so this change mimics that behavior.
=> Set default "Accept-Language" header

android/src/main/java/com/getcapacitor/plugin/http/FilesystemUtils.java, android/src/main/java/com/getcapacitor/plugin/http/HttpRequestHandler.java
- Fixes #183, where if you do not specify the `method` parameter to `Http.uploadFile` then it always returns an error, by defaulting to POST like iOS does.
- Fixes a bug where you cannot specify a `file://` URI as the `filePath` parameter on Android, which works on iOS.
=> Fix android http upload bugs

android/src/main/java/com/getcapacitor/plugin/http/CapacitorCookieManager.java, android/src/main/java/com/getcapacitor/plugin/http/Http.java, ios/Plugin/CapacitorCookieManager.swift, ios/Plugin/Plugin.m, ios/Plugin/Plugin.swift, src/definitions.ts, src/web.ts
This PR fixes the following cookies issues:
- Fix `setCookie()` on android. Currently, it is not possible to set a Set-Cookie HTTP response header as part of the cookie value due to the encoding step. For instance, setting a cookie with the value `en; Max-Age=5` will be replaced to `en%3B+Max-Age%3D5` and hence Max-Age will not be taken into account. Thus, this PR removes the encoding/decoding steps on android.
- `clearCookies()` on android is implemented differently than on ios. On android all cookies are removed, on ios only those from the passed URL. This PR fixes this issue by introducing a new method `clearAllCookies()` and adjusting the respective methods on android/ios.
- Fix definition for getCookiesMap and add implementation for `getCookiesMap()` on ios.
=> Fix various cookies issues

README.md
`FilesystemDirectory` is deprecated and got replaced by `Directory`.
=> docs(readme): update file directory enum

android/src/main/java/com/getcapacitor/plugin/http/HttpRequestHandler.java
Added reading the option "shouldEncodeUrlParams" from JS and passed it on to setParams.
Fixed URL formatting in setParams when no encoding.
Added early return in setParams if params are empty, and skipped the URL formatting altogether.
This should fix #62 and #101
=> Android: Ensure proper URL formatting without encoding, skip setParams if empty
